# Generated by Django 4.0 on 2022-05-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_description', models.CharField(max_length=100, verbose_name='描述')),
                ('account_name', models.CharField(max_length=50, verbose_name='账户名')),
                ('account_password', models.CharField(max_length=50, verbose_name='密码')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='创建日期')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='修改日期')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
            ],
            options={
                'db_table': 'my_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_hero_name', models.CharField(max_length=100, verbose_name='演员名称')),
                ('movie_date', models.DateField(verbose_name='发布日期')),
                ('movie_film_name', models.CharField(max_length=100, verbose_name='影片名称')),
                ('movie_img', models.CharField(max_length=200, verbose_name='图片路径')),
            ],
        ),
    ]
