# Generated by Django 4.0 on 2022-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_evaluate',
            field=models.CharField(default='没有添加评价', max_length=200, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(upload_to='', verbose_name='图片路径'),
        ),
    ]
