# Generated by Django 4.0 on 2022-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_movie_movie_evaluate_alter_movie_movie_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.AlterModelOptions(
            name='myaccount',
            options={'managed': False, 'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_img',
            field=models.ImageField(upload_to='account', verbose_name='图片路径'),
        ),
    ]
